<div class="nav">
    <a href="#" class="nav__trigger">
        <div class="bars"></div>
    </a> 
    <div class="nav__content" >
        <nav class="nav__list">
            <ul>
                <li class="nav__item"><a href="./">Lections</a></li>
				<li class="nav__item"><a href="./?homework">Homework</a></li>
                <li class="nav__item"><a href="99.php">Manage</a></li> 
                <li class="nav__item"><a href="help.php">User manual</a></li>
            </ul>
        </nav>
    </div>    
</div>